# -*- coding: utf-8 -*-
"""lista.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZAobzs3wk2mYxwXMKsAOtN9rwLMmpxjr

Exercicio 001
"""

n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número:  '))

soma = n1 + n2

print(f'A soma dos valores são {soma}')

"""Exercicio 002

"""

n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número:  '))
n3 = int(input('Digite o terceiro número:  '))

if n1 >= n2 and n1 >= n3:
    maior = n1
elif n2 >= n1 and n2 >= n3:
    maior = n2
else :
    maior = n3


print(f'O maior número é {maior}')

"""Exercicio 003"""

n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))
n3 = int(input('Digite o terceiro número: '))

if n1 <= n2 and n1 <= n3:
    menor = n1
elif n2 <= n1 and n2 <= n3:
    menor = n2
else:
    menor = n3

print(f'O menor número é {menor}')

"""Exercicio 004

"""

print("Qual o seu nivel mediante alerta de risco")

n1 = int(input('Qual o nível que você se encontra? '))

if n1 >= 9:
    print('O seu nível é grave, procuro uma ajuda')
else :
    print('O seu nível está normal')

"""Exercicio 005

"""

print("Qual o seu nivel mediante alerta de risco")

n1 = int(input('Qual o nível que você se encontra? '))

if n1 >= 0 and n1 <= 10:
    if n1 >= 9:
        print('O seu nível é grave, procuro uma ajuda')
    else :
        print('O seu nível está normal')
else:
    print('ERRO!, o valor informado não condiz com nossos parâmetros.')

"""Exercicio 006"""

print("Qual o seu nivel mediante alerta de risco")

n1 = int(input('Qual o nível que você se encontra? '))

if n1 >= 0 and n1 <= 9:
    if n1 >= 0 and n1 <= 3:
        print('O seu nível é baixo')
    elif n1 >= 4 and n1 <= 6:
        print('O seu nível é médio')
    elif n1 >= 7 and n1 <= 9:
        print('O seu nível é alto')
else:
    print('O seu nível está GRAVE!')

"""Exercicio 007"""

n1 = int(input('Digite um número: '))
n2 = int(input('Digite um número: '))
n3 = int(input('Digite um número: '))

if n1 % n2 == 0 or n1 % n3 == 0 or n2 % n1 == 0 or n2 % n3 == 0 or n3 % n1 == 0 or n3 % n2 ==0:
  print('Possui numeros multiplos')
else:
  print('Não possui numeros multiplos')

"""Exercicio 008"""

##Algoritimo para saber qual a categoria de um triângulo

cateto1 = float(input('Qual o valor do cateto 1: '))
cateto2 = float(input('Qual o valor do cateto 2: '))
hipotenusa = float(input('Qual o valor do hipotenusa: '))

somaCateto = cateto1 + cateto2

if somaCateto > hipotenusa:
  if cateto1 == cateto2 and cateto2 == hipotenusa:
    print('Este triângulo e equilátero')
  elif cateto1 == cateto2 or cateto1 == hipotenusa or cateto2 == hipotenusa:
    print('Este4 triângulo é isósceles')
  elif cateto1 != cateto2 and cateto1 != hipotenusa and cateto2 != hipotenusa:
    print('Este4 triângulo é escaleno')
else:
  print('Isto não é um triângulo. ')

"""Exercicio 009"""

##Area de um triângulo

base = float(input('Qual o tamanho da base do triângulo: '))
altura = float(input('Qual a altura do triângulo: '))

area = (base * altura) / 2

print(f'A área do triângulo é {area}')

"""Exercicio 010"""

##Sistema de aprovação dos alunos de uma universidade

nota1 = float(input('Informe sua primeira nota: '))
nota2 = float(input('Informe sua segunda nota: '))
nota3 = float(input('Informe sua terceira nota: '))
nota4 = float(input('Informe sua quarta nota: '))

media = (nota1 + nota2 + nota3 + nota4) / 4

if media >= 60:
    print(f'\n Parabéns! A sua média foi de {media}. Você foi aprovado.')
else:
    print(f'Você está reprovado. A sua média foi de {media}')

"""Exercicio 011"""

##Algoritimo para verificar se o aluno está aprovado e validar a media ponderada das notas informadas


peso1 = float(input('Informe o peso da primeira nota: '))
peso2 = float(input('Informe o peso da segunda nota: '))
peso3 = float(input('Informe o peso da terceira nota: '))
peso4 = float(input('Informe o peso da quarta nota: '))

somaPesos = peso1 + peso2 + peso3 + peso4

if somaPesos != 10:
    print('\nA soma de pesos tem que ser igual a 10. Por favor informe novamente os valores.')
    peso1 = float(input('\nInforme o peso da primeira nota: '))
    peso2 = float(input('Informe o peso da segunda nota: '))
    peso3 = float(input('Informe o peso da terceira nota: '))
    peso4 = float(input('Informe o peso da quarta nota: '))
else :
    print('\n Agora informe os valores das notas de cada avaliação.')
    nota1 = float(input('Informe sua primeira nota: '))
    nota2 = float(input('Informe sua segunda nota: '))
    nota3 = float(input('Informe sua terceira nota: '))
    nota4 = float(input('Informe sua quarta nota: '))

    somaNotas = (nota1 * peso1) + (nota2 * peso2) + (nota3 * peso3) + (nota4 * peso4)
    mediaPonderada = somaNotas / somaPesos

    if mediaPonderada >= 60:
        print(f'\nParabéns! A sua média foi de {mediaPonderada} você foi aprovado.')
    else:
        print(f'Você está reprovado. A sua média foi de {mediaPonderada}')


##Algoritimo para verificar se o aluno está aprovado e validar a media ponderada das notas informadas
"""
somaPesos = 0

while somaPesos != 10:
    peso1 = float(input('\nInforme o peso da primeira nota: '))
    peso2 = float(input('Informe o peso da segunda nota: '))
    peso3 = float(input('Informe o peso da terceira nota: '))
    peso4 = float(input('Informe o peso da quarta nota: '))

    somaPesos = peso1 + peso2 + peso3 + peso4

    if somaPesos != 10:
        print('\nA soma de pesos tem que ser igual a 10. Por favor informe novamente os valores.')

print('\n Agora informe os valores das notas de cada avaliação.')
nota1 = float(input('Informe sua primeira nota: '))
nota2 = float(input('Informe sua segunda nota: '))
nota3 = float(input('Informe sua terceira nota: '))
nota4 = float(input('Informe sua quarta nota: '))

somaNotas = (nota1 * peso1) + (nota2 * peso2) + (nota3 * peso3) + (nota4 * peso4)
mediaPonderada = somaNotas / somaPesos

if mediaPonderada >= 60:
    print(f'\nParabéns! A sua média foi de {mediaPonderada} você foi aprovado.')
else:
    print(f'Você está reprovado. A sua média foi de {mediaPonderada}')
"""

"""Exercicio 012"""

print("Pense em um animal e responda com 'sim' ou 'não' às perguntas a seguir:")

pergunta1 = input("O animal voa? ")
if pergunta1.lower() == "sim":
    pergunta2 = input("O animal é uma ave de rapina? ")
    if pergunta2.lower() == "sim":
        animal = "águia"
    else:
        animal = "pato"
elif pergunta1.lower() == "não":
    pergunta3 = input("O animal é um mamífero? ")
    if pergunta3.lower() == "sim":
        pergunta4 = input("O animal é um carnívoro? ")
        if pergunta4.lower() == "sim":
            pergunta5 = input("O animal é grande? ")
            if pergunta5.lower() == "sim":
                animal = "leão"
            else:
                animal = "gato"
        else:
            pergunta6 = input("O animal é um mamífero aquático? ")
            if pergunta6.lower() == "sim":
                pergunta7 = input("O animal é uma baleia? ")
                if pergunta7.lower() == "sim":
                    animal = "baleia"
                else:
                    pergunta8 = input("O animal é um ornitorrinco? ")
                    if pergunta8.lower() == "sim":
                        animal = "ornitorrinco"
                    else:
                        animal = "onça pintada"
            else:
                pergunta9 = input("O animal vive na água? ")
                if pergunta9.lower() == "sim":
                    pergunta10 = input("O animal é um peixe? ")
                    if pergunta10.lower() == "sim":
                        pergunta11 = input("O animal é um tubarão? ")
                        if pergunta11.lower() == "sim":
                            animal = "tubarão"
                        else:
                            animal = "lambari"
                    else:
                        pergunta12 = input("O animal é uma enguia? ")
                        if pergunta12.lower() == "sim":
                            animal = "enguia"
                        else:
                            pergunta13 = input("O animal é uma arraia? ")
                            if pergunta13.lower() == "sim":
                                animal = "arraia"
                            else:
                                animal = "pinguim"
                else:
                    pergunta14 = input("O animal é um morcego? ")
                    if pergunta14.lower() == "sim":
                        animal = "morcego"
                    else:
                        pergunta15 = input("O animal é uma galinha? ")
                        if pergunta15.lower() == "sim":
                            animal = "galinha"
                        else:
                            pergunta16 = input("O animal é um avestruz? ")
                            if pergunta16.lower() == "sim":
                                animal = "avestruz"
                            else:
                                animal = "onça pintada"
else:
    animal = "animal não identificado"

print(f"O animal que você está pensando é um(a) {animal}.")

"""Exercicio 013"""

n1 = int(input('Digite um número: '))
n2 = int(input('Digite um número: '))
n3 = int(input('Digite um número: '))

if n1 <= n2 and n1 <= n3:
    menor = n1
    if n2 <= n3:
        meio = n2
        maior = n3
    else:
        meio = n3
        maior = n2
elif n2 <= n1 and n2 <= n3:
    menor = n2
    if n1 <= n3:
        meio = n1
        maior = n3
    else:
        meio = n3
        maior = n1
else:
    menor = n3
    if n1 <= n2:
        meio = n1
        maior = n2
    else:
        meio = n2
        maior = n1

print(f'Os números en ordem crescente são: {menor}, {meio}, {maior}')

"""Exercicio 014"""

n1 = int(input('Digite um número: '))
n2 = int(input('Digite um número: '))
n3 = int(input('Digite um número: '))

if n1 <= n2 and n1 <= n3:
    menor = n1
    if n2 <= n3:
        meio = n2
        maior = n3
    else:
        meio = n3
        maior = n2
elif n2 <= n1 and n2 <= n3:
    menor = n2
    if n1 <= n3:
        meio = n1
        maior = n3
    else:
        meio = n3
        maior = n1
else:
    menor = n3
    if n1 <= n2:
        meio = n1
        maior = n2
    else:
        meio = n2
        maior = n1

print(f'Os números en ordem decrescente são: {maior}, {meio}, {menor}')

"""Exercicio 015"""

numeroMatricula = int(input('Qual o número de sua matrícula:  '))

if numeroMatricula > 99999:
    print('o número informado ultrapassa 5 digítos, digite novamente sua matrícula.')
    numeroMatricula = int(input('Qual o número de sua matrícula:  '))

nomeCompleto = input('Qual seu nome completo: ')
genero = input('Qual o seu genêro (M(masculino) e F(feminino)):  ')
curso = input('Qual o curso que você está realizando(“BES”, “BEC” ou “ADS"):  ')
coeficiente = float(input('Qual o seu coeficiente de desempenho:  '))



if genero.upper() == 'M':
    generoC = 'Masculino'
elif genero.upper() == 'F':
    generoC = 'Feminino'
else:
    generoC = 'Indeterminado'

if curso.upper() == 'BES':
    nomeCurso = 'Bacharelado em Engenharia de Software'
elif curso.upper() == 'BEC':
    nomeCurso = 'Bacharelado em Engenharia de Computação'
elif curso.upper() == 'ADS':
    nomeCurso = 'Analise e Desenvolvimento de Sistemas'
else:
    nomeCurso = 'Curso não encontrado em nossa base de dados'

'''
if coeficiente >= 0 and coeficiente <= 100:
    if coeficiente >= 90 and coeficiente <= 100:
        coeficienteAluno = 'Excelente'
    elif coeficiente >= 70 and coeficiente < 90:
        coeficienteAluno = 'Bom'
    elif coeficiente >= 50 and coeficiente < 70:
        coeficienteAluno = 'Regular'
    elif coeficiente >= 30 and coeficiente < 50:
        coeficienteAluno = 'Necessita melhoras'
    else:
        coeficienteAluno = 'Preocupante'
else:
    print('Valor inválido!')
'''

if 0 <= coeficiente <= 100:
    if 90 <= coeficiente <= 100:
            coeficienteAluno = 'Excelente'
    elif 70 <= coeficiente < 90:
            coeficienteAluno = 'Bom'
    elif 50 <= coeficiente < 70:
            coeficienteAluno = 'Regular'
    elif 30 <= coeficiente < 50:
            coeficienteAluno = 'Necessita melhoras'
    else:
            coeficienteAluno = 'Preocupante'
else:
    coeficienteAluno = 'Valor inválido'



print(f'\n Nome completo: {nomeCompleto}')
print(f'O número da matrícula é: {numeroMatricula}')
print(f'Genêro: {generoC}')
print(f'Curso: {nomeCurso}')
print(f'Coeficiente de redimento: {coeficienteAluno}')

"""Exercicio 016"""

##Algoritimo para saber a temperatura em Cº ou Fº.

valor = float(input('Qual a temperatura atual: '))
temp = input('Em qual temperatura vocês está agora, Farenheit(f) ou Celsius(c): ')

## C=(F-32)/1,8

if temp.upper() == 'F':
  newTemp = (valor - 32) / 1.8
  print(f'A temperatura em Celsius é {newTemp}º')
elif temp.upper() == 'C':
  newTemp = (valor * 1.8) + 32
  print(f'A temperatura em Farenheit é {newTemp}º')
else:
  print('A temperatura digita acima não está no nosso sistema')

"""Exercicio 017"""

dia = int(input('Qual o dia de hoje: '))
mes = int(input('Qual o mês: '))
ano = int(input('Qual o ano: '))

if dia < 30:
  dia += 1
elif mes == 12:
  dia = 1
  mes = 1
  ano += 1
elif dia == 30:
  dia = 1
  mes += 1
else:
  print('Informe uma data valida')

print(f'O proximo dia será {dia}/{mes}/{ano}')

"""Exercicio 018"""

dia = int(input('Qual o dia de hoje: '))
mes = int(input('Qual o mês: '))
ano = int(input('Qual o ano: '))

if 1 <= dia <= 30 and 1 <= mes <= 12:
    if dia == 1:
        if mes == 1:
            dia = 30
            mes = 12
            ano -= 1
        else:
            dia = 30
            mes -= 1
    else:
        dia -= 1
else:
    print("Data inserida inválida.")

print(f'O dia anterior será {dia}/{mes}/{ano}')

"""Exercicio 019"""

##Programa para saber o valor a se pagar em um valor parcelado

valor = float(input('Qual o valor da compra: R$'))
prest = int(input('Quantas prestações você irá dividir: '))

if prest >= 12:
  if prest >= 12 and prest <= 24:
    valorJuros = (valor * 10) / 100
    novoValor = valor + valorJuros
    print(f'O valor final do produto será de R${novoValor}')
  elif prest >= 25 and prest <= 36:
    valorJuros = (valor * 15) / 100
    novoValor = valor + valorJuros
    print(f'O valor final do produto será de R${novoValor}')
  else:
    print('Você ultrapassou o número de pretações')
else:
  print(f'O produto não sofrerá alterações de valor.')

"""Exercicio 020"""

print("Abaixo você colocará o valor de sua venda para saber qual será a sua comissão.")

venda = float(input('Qual o valor da venda: '))

if venda >= 100000:
    pctVend = (venda/100) * 16
    comissao = 700.00 + pctVend

elif venda < 100000 and venda >= 80000:
    pctVend = (venda/100) * 14
    comissao = 650 + pctVend

elif venda < 80000 and venda >= 60000:
    pctVend = (venda/100) * 14
    comissao = 600 + pctVend

elif venda < 60000 and venda >= 40000:
    pctVend = (venda/100) * 14
    comissao = 550 + pctVend

elif venda < 40000 and venda >= 20000:
    pctVend = (venda/100) * 14
    comissao = 500 + pctVend

elif venda < 20000 :
    pctVend = (venda/100) * 14
    comissao = 400 + pctVend

print(f'O valor que será pago ao vendedor seserá de {comissao}')