-- MySQL Script generated by MySQL Workbench
-- Tue Nov  5 14:47:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pwplanopag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pwplanopag` (
  `codplpagamento` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  `numdias` INT NOT NULL,
  `status` CHAR(1) NOT NULL,
  PRIMARY KEY (`codplpagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pwcliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pwcliente` (
  `codcliente` INT NOT NULL AUTO_INCREMENT,
  `cliente` VARCHAR(200) NOT NULL,
  `fantasia` VARCHAR(200) NOT NULL,
  `dtcadastro` DATE NOT NULL,
  `tipopessoa` CHAR(1) NOT NULL,
  `codtelefone` INT NOT NULL,
  `codendereco` INT NOT NULL,
  PRIMARY KEY (`codcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pwempregado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pwempregado` (
  `codempr` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `dtinicio` DATE NOT NULL,
  `dtfim` DATE NULL,
  `dtnascimento` DATE NOT NULL,
  `codtelefone` INT NOT NULL,
  `codendereco` INT NOT NULL,
  `obs` VARCHAR(250) NULL,
  PRIMARY KEY (`codempr`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pwpedidoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pwpedidoc` (
  `codpedido` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `codcliente` INT NOT NULL,
  `codempr` INT NOT NULL,
  `mediadesc` DECIMAL(4,2) NOT NULL,
  `vltotal` DECIMAL(18,4) NOT NULL,
  `vldesconto` DECIMAL(18,4) NOT NULL,
  `codplpagamento` INT NOT NULL,
  `pwplanopag_codplpagamento` INT NOT NULL,
  PRIMARY KEY (`codpedido`, `pwplanopag_codplpagamento`),
  INDEX `fk_pwpedidoc_pwplanopag1_idx` (`pwplanopag_codplpagamento` ASC) VISIBLE,
  INDEX `fk_pwpedidoc_cliente_idx` (`codcliente` ASC) VISIBLE,
  INDEX `fk_pwpedidoc_empregado_idx` (`codempr` ASC) VISIBLE,
  CONSTRAINT `fk_pwpedidoc_pwplanopag1`
    FOREIGN KEY (`pwplanopag_codplpagamento`)
    REFERENCES `mydb`.`pwplanopag` (`codplpagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pwpedidoc_cliente`
    FOREIGN KEY (`codcliente`)
    REFERENCES `mydb`.`pwcliente` (`codcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pwpedidoc_empregado`
    FOREIGN KEY (`codempr`)
    REFERENCES `mydb`.`pwempregado` (`codempr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pwfornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pwfornecedor` (
  `codfornec` INT NOT NULL AUTO_INCREMENT,
  `fornecedor` VARCHAR(200) NOT NULL,
  `fantasia` VARCHAR(200) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `dtcadastro` DATE NOT NULL,
  `codtelefone` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `codendereco` INT NOT NULL,
  `nome_representante` VARCHAR(100) NOT NULL,
  `email_representante` VARCHAR(100) NOT NULL,
  `telefone_representante` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codfornec`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pwproduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pwproduto` (
  `codproduto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  `codfornec` INT NOT NULL,
  `vlunit` DECIMAL(18,4) NOT NULL,
  `embalagem` VARCHAR(40) NOT NULL,
  `gtin` VARCHAR(2) NOT NULL,
  `ean` VARCHAR(20) NOT NULL,
  `dtcadastro` DATE NOT NULL,
  PRIMARY KEY (`codproduto`),
  INDEX `fk_pwproduto_pwfornecedor1_idx` (`codfornec` ASC) VISIBLE,
  CONSTRAINT `fk_pwproduto_pwfornecedor1`
    FOREIGN KEY (`codfornec`)
    REFERENCES `mydb`.`pwfornecedor` (`codfornec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pwpedidoi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pwpedidoi` (
  `codpedido` INT NOT NULL,
  `data` DATE NOT NULL,
  `codcliente` INT NOT NULL,
  `codproduto` INT NOT NULL,
  `qtd` DECIMAL(18,2) NOT NULL,
  `desconto` DECIMAL(4,2) NOT NULL,
  `vlunit` DECIMAL(18,4) NOT NULL,
  `vltotal` DECIMAL(18,4) NOT NULL,
  INDEX `fk_pwpedidoi_codprod_idx` (`codproduto` ASC) VISIBLE,
  INDEX `fk_pwpedidoi_pwpedidoc1_idx` (`codpedido` ASC) VISIBLE,
  INDEX `fk_pwpedidoi_cliente_idx` (`codcliente` ASC) VISIBLE,
  CONSTRAINT `fk_pwpedidoi_codprod`
    FOREIGN KEY (`codproduto`)
    REFERENCES `mydb`.`pwproduto` (`codproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pwpedidoi_pwpedidoc1`
    FOREIGN KEY (`codpedido`)
    REFERENCES `mydb`.`pwpedidoc` (`codpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pwpedidoi_cliente`
    FOREIGN KEY (`codcliente`)
    REFERENCES `mydb`.`pwcliente` (`codcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pwclientefisico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pwclientefisico` (
  `codcliente` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  INDEX `fk_pwclientefisico_pwcliente1_idx` (`codcliente` ASC) VISIBLE,
  PRIMARY KEY (`codcliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  CONSTRAINT `fk_pwclientefisico_pwcliente1`
    FOREIGN KEY (`codcliente`)
    REFERENCES `mydb`.`pwcliente` (`codcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pwclientejuridico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pwclientejuridico` (
  `codcliente` INT NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `inscricaoestadual` VARCHAR(20) NOT NULL,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  PRIMARY KEY (`codcliente`),
  CONSTRAINT `fk_pwclientejuridico_pwcliente1`
    FOREIGN KEY (`codcliente`)
    REFERENCES `mydb`.`pwcliente` (`codcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
